name: Deploy to Minikube using GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Docker image and deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
      
      - name: Check Minikube status
        run: minikube status
      
      - name: Build Docker image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          docker images
          
      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml
      
      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
